imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: images.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        # Global twig vars
        cherez_web__project__url__protocol: "%cherez_web__project__url__protocol%"
        cherez_web__project__url__host: "%cherez_web__project__url__host%"
        cherez_web__project__logo_path: "%cherez_web__project__logo_path%"
        cherez_web__project__company__name: "%cherez_web__project__company__name%"
        cherez_web__project__company__start_year: "%cherez_web__project__company__start_year%"
        cherez_web__project__company__url__protocol: "%cherez_web__project__company__url__protocol%"
        cherez_web__project__company__url__host: "%cherez_web__project__company__url__host%"
        cherez_web__project__name: "%cherez_web__project__name%"
        cherez_web__project__title: "%cherez_web__project__title%"
        cherez_web__project__email__noreply__mail: "%cherez_web__project__email__noreply__mail%"
        cherez_web__project__email__support: "%cherez_web__project__email__support%"
        cherez_web__service__redirect__index_route: "%cherez_web__service__redirect__index_route%"
        cherez_web__service__redirect__cp_index_route: "%cherez_web__service__redirect__cp_index_route%"
        cherez_web__project__counter__google_analytics: "%cherez_web__project__counter__google_analytics%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [CherezWebDefaultBundle, CherezWebServiceBundle, CherezWebProjectBundle, MopaBootstrapBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/bin/uglifyjs
        uglifycss:
            bin: /usr/bin/uglifycss
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            utcdatetime: Extensions\Doctrine\DBAL\Types\UTCDateTimeType
        mapping_types: 
            enum:   string
            datetime:   utcdatetime   
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

gregwar_captcha:
  width: 139
  invalid_message: "Вы допустили ошибку при вводе кода, повторите попытку."
  background_color: [255, 255, 255]
  charset: 0123456789

mopa_bootstrap:
    form: # Adds twig form theme  support
        templating: true # default is true
#        render_fieldset: true # default is true
#        render_collection_item: true # default is true
        show_legend: false # default is true
#        show_child_legend: false # default is false
#        render_required_asterisk: true # default is true
#        checkbox_label: 'both' # default is both (label|widget|both)
#        error_type: 'block' # or inline which is default / default is null
#        collection:
#            widget_remove_btn:
#                attr:
#                    class: btn
#                icon: null
#                icon_inverted: false
#            widget_add_btn:
#                attr:
#                    class: btn
#                icon: null
#                icon_inverted: false

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
#        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        pagination: MopaBootstrapBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template