security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        CherezWeb\ServiceBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: admin1pass, roles: [ 'ROLE_ADMIN' ] }
        in_database:
            entity: { class: CherezWebServiceBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        all_site:
            provider: in_database
            pattern:    ^/
            form_login:
                check_path: /security/login_check
                login_path: /security/login
                default_target_path: /security/login_final
                always_use_default_target_path: true
                username_parameter: LoginType[email] #поменять вместе с формой авторизации
                password_parameter: LoginType[password] #поменять вместе с формой авторизации
                remember_me: true
            logout:
                path:   /security/logout
                target: /security/logout_final
            remember_me:
                always_remember_me: true
                key:        "%secret%"
#                lifetime:   3600 #длительность. по умолчанию максимальная
                path:   /
                domain: ~
#                remember_me_parameter: _remember_me #поменять вместе с формой авторизации
            anonymous: ~

#    access_control:
#        - { path: ^/cp, roles: IS_AUTHENTICATED_REMEMBERED }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }